### ISSUE TITLE
[jss-cli] back and forth conversion between jss & css

### ISSUE THREAD

**Issue by jsakas** [cssinjs/jss#1225]
__Expected behavior:__

I believe the expected behaviour would be you can convert a jss file created from jss-cli back to css.

__Describe the bug:__

Following the documentation at: https://cssinjs.org/cli/?v=v5.0.2

I have a CSS file `style.css` with the following:

```
body {
    background: blue;
}

.test {
    color: green;
}
```

I run `jss convert source.css -f js -e cjs > source.js`, which produces `source.js` with the contents:

```
module.exports = {
  '@global': {
    body: {
      background: 'blue'
    },
    '.test': {
      color: 'green'
    }
  }
};
```

Now, I would expect to be able to convert this file back to CSS using the CLI as demonstrated by the documentation.

`jss convert source.js -f css > source.css`

```
ReferenceError: source is not defined
    at evalmachine.<anonymous>:1:1
    at Script.runInContext (vm.js:134:20)
    at Object.runInContext (vm.js:297:6)
    at module.exports (/Users/jonsakas/.nvm/versions/node/v12.5.0/lib/node_modules/jss-cli/lib/execModule.js:6:6)
    at convert (/Users/jonsakas/.nvm/versions/node/v12.5.0/lib/node_modules/jss-cli/bin/jss.js:34:15)
    at Command.onConvert (/Users/jonsakas/.nvm/versions/node/v12.5.0/lib/node_modules/jss-cli/bin/jss.js:82:26)
    at Command.listener (/Users/jonsakas/.nvm/versions/node/v12.5.0/lib/node_modules/jss-cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:200:13)
    at Command.parseArgs (/Users/jonsakas/.nvm/versions/node/v12.5.0/lib/node_modules/jss-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/jonsakas/.nvm/versions/node/v12.5.0/lib/node_modules/jss-cli/node_modules/commander/index.js:474:21)
```

__Versions (please complete the following information):__
 - jss: v10.0.0
 - jss-cli: v5.0.2
 - Node: v12.5.0
 - OS: OSX v10.14.6

**Comment by Max-Jefferson** [comment]
I hade the same issue, putting in the full path stopped that error but introduced the error: 

> SyntaxError: Unexpected end of input
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at Object.runInContext (vm.js:289:10)
    at module.exports (C:\Users\Max Jefferson\AppData\Roaming\npm\node_modules\jss-cli\lib\execModule.js:6:6)
    at convert (C:\Users\Max Jefferson\AppData\Roaming\npm\node_modules\jss-cli\bin\jss.js:34:15)
    at Command.onConvert (C:\Users\Max Jefferson\AppData\Roaming\npm\node_modules\jss-cli\bin\jss.js:82:26)
    at Command.listener (C:\Users\Max Jefferson\AppData\Roaming\npm\node_modules\jss-cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (C:\Users\Max Jefferson\AppData\Roaming\npm\node_modules\jss-cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\Max Jefferson\AppData\Roaming\npm\node_modules\jss-cli\node_modules\commander\index.js:474:21)

**Comment by kof** [comment]
Please reopen if still valid
