### ISSUE TITLE
npm i jss-default-preset ===> npm ERR! code E404

### ISSUE THREAD

**Issue by tomtom94** [cssinjs/jss#1311]
Can't install you module `jss-default-preset`

```
npm i jss-default-preset
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jss-default-preset - Not found
npm ERR! 404 
npm ERR! 404  'jss-default-preset@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomtom94/.npm/_logs/2020-03-16T11_10_00_311Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.10.0/bin/node',
1 verbose cli   '/Users/tomtom94/.npm-global/bin/npm',
1 verbose cli   'i',
1 verbose cli   'jss-default-preset'
1 verbose cli ]
2 info using npm@6.13.0
3 info using node@v12.10.0
4 verbose npm-session 1b0999612bb6abe7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/jss-default-preset 192ms
8 http fetch GET 404 https://registry.npmjs.org/jss-default-preset 61ms
9 silly fetchPackageMetaData error for jss-default-preset@latest 404 Not Found - GET https://registry.npmjs.org/jss-default-preset - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 1348ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/jss-default-preset - Not found
12 verbose stack     at /Users/tomtom94/.npm-global/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid jss-default-preset@latest
15 verbose cwd /Users/tomtom94/Code/footballmotion
16 verbose Darwin 18.5.0
17 verbose argv "/usr/local/Cellar/node/12.10.0/bin/node" "/Users/tomtom94/.npm-global/bin/npm" "i" "jss-default-preset"
18 verbose node v12.10.0
19 verbose npm  v6.13.0
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/jss-default-preset - Not found
22 error 404
23 error 404 'jss-default-preset@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
```

**Comment by kof** [comment]
Where did you find this package name?

**Comment by kof** [comment]
The actual name is https://www.npmjs.com/package/jss-preset-default

**Comment by tomtom94** [comment]
ok thanks.

**Comment by kof** [comment]
I mean it, where did you get the wrong name? It's a documentation or something that needs to be fixed?

**Comment by tomtom94** [comment]
<img width="1393" alt="Capture d’écran 2020-03-16 à 12 30 05" src="https://user-images.githubusercontent.com/262550/76754143-e7770300-6781-11ea-8b5c-3748fe7c598f.png">
Enjoy bro

**Comment by kof** [comment]
> Enjoy bro

Mind explaining?
