### ISSUE TITLE
[react-jss]

### ISSUE THREAD

**Issue by altgifted** [cssinjs/jss#1395]
Problem with testing react with jest. I am getting this error whenever I use jss in a component.

![Screenshot from 2020-09-23 17-41-26](https://user-images.githubusercontent.com/30584905/94021237-ffd57380-fddd-11ea-996e-c9d256e1d388.png)

Also i have a valid config for jest:

```
{
  "moduleDirectories": [
    "node_modules",
    "src"
  ],
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "jsx",
    "json",
    "node"
  ],
  "moduleNameMapper": {
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|pdf)$": "identity-obj-proxy"
  },
  "preset": "ts-jest",
  "roots": [
    "<rootDir>/src"
  ],
  "setupFilesAfterEnv": [
    "<rootDir>/src/setupTests.js"
  ],
  "testEnvironment": "jsdom",
  "testMatch": [
    "<rootDir>/src/**/__tests__/**/*.{ts,tsx}",
    "<rootDir>/src/**/*(*.)(spec|test).{ts,tsx",
    "<rootDir>/test/**/*.{ts,tsx",
    "<rootDir>/test/**/?(*.)(spec|test).{ts,tsx"
  ],
  "transform": {
    "^.+\\.tsx?$": "ts-jest",
    "^.+\\.jsx?$": "babel-jest"
  },
  "verbose": true
}
```

**Comment by playfulpachyderm** [comment]
I'm getting this problem too, and despite a lot of searching, I haven't found any workarounds for it.  It seems like until this is addressed I won't be able to use JSS.

**Comment by kof** [comment]
You are not getting this same error when you import any other library, only jss?

**Comment by kof** [comment]
I suspect you have transpiled your test file, but the lib code is not transpiled and you are trying to load ESM version into environment that doesn't support esm.

I don't know how other libraries which have module keyword with esm code in the dist do this. Possible solution is to enable modules in your node instance. Another possible solution is to use require in your tests, I am guessing it would be loading the commonjs version.

cc @TrySound

**Comment by TrySound** [comment]
Jest does not look into `module` field. This should not be a problem. Maybe something in babel config may give some light. Could anybody provide a reproduction example? It's hard to guess without more information.

**Comment by kof** [comment]
If we can say for sure that this is not a problem with JSS build and the problem is with jest/babel, then this question should be asked somewhere else.

**Comment by smarschollek** [comment]
i stumbled upon same SyntaxError - are there any clues or other discussions about that topic besides that it is maybe linked to jest/babel ?

**Comment by LordTony** [comment]
I've found that adding

`
    transformIgnorePatterns: [
        "node_modules/(?!(react-jss)/)"
    ]
`

into my jest.config.js file gets me part of the way there, but then I just end up with

`
    SyntaxError: C:\Users\tony.santi\source\repos\SureViewGit\SureViewReact\node_modules\react-jss\src\jss.js: Unexpected token, expected "," (2:21)

       1 | // @flow
     > 2 | import {create, type Jss} from 'jss'
         |                      ^
       3 | import preset from 'jss-preset-default'
       4 | 
       5 | const jss: Jss = create(preset())

      at Object._raise (node_modules/@babel/parser/src/parser/error.js:60:45)
      at Object.raiseWithData (node_modules/@babel/parser/src/parser/error.js:55:17)
      at Object.raise (node_modules/@babel/parser/src/parser/error.js:39:17)
      at Object.unexpected (node_modules/@babel/parser/src/parser/util.js:139:16)
      at Object.expect (node_modules/@babel/parser/src/parser/util.js:116:28)
      at Object.parseNamedImportSpecifiers (node_modules/@babel/parser/src/parser/statement.js:2356:14)
      at Object.parseImport (node_modules/@babel/parser/src/parser/statement.js:2137:39)
      at Object.parseStatementContent (node_modules/@babel/parser/src/parser/statement.js:246:25)
      at Object.parseStatement (node_modules/@babel/parser/src/parser/statement.js:157:17)
      at Object.parseBlockOrModuleBlockBody (node_modules/@babel/parser/src/parser/statement.js:874:25)
`

No idea what is going on here and like everyone else in this thread, I can't find anything helpful out there for how to work around this.

**Comment by jasmaa** [comment]
I was able to reproduce the error [here](https://github.com/jasmaa/react-jss-example). It looks like the issue is from a conflict between `node_modules/react-jss/src/jss.js` and `node_modules/jss`. Jest tries to use `node_modules/react-jss/src/jss.js` first instead of `node_modules/jss` which is causing the error. When I renamed `node_modules/react-jss/src/jss.js` to something else, the error went away.

Only workaround I found is to create a version conflict by installing a version of `jss` different from the `react-jss` version I currently had. This added a nested `node_modules` within `node_modules/react-jss` which `react-jss` consumed `jss` from instead of from `src`.

**Comment by pnpetrov** [comment]
I was looking at a repository with the same issue. The issue was with wrongly configured module directories. Including `src` in the `moduleDirectories` config means that all `src` directories can be used recursively for resolving module's location when you probably want to target only the root `src` directory.

Changing the `moduleDirectories` config from
```
"moduleDirectories": [
    "node_modules",
    "src"
]
```

to 

```
"moduleDirectories": [
    "node_modules",
    "<rootDir>/src"
]
```

should be enough to resolve the `jss` module resolution
