### ISSUE TITLE
The official "setup" example crashes with "preset is not a function"

### ISSUE THREAD

**Issue by jameshfisher** [cssinjs/jss#1569]
__Expected behavior:__
The official "setup" example works

__Describe the bug:__
The official "setup" example crashes

__Reproduction:__ 

```
npm install jss jss-preset-default
```

Create `test.js`:

```
import jss from 'jss'
import preset from 'jss-preset-default'

jss.setup(preset())

// Create your style.
const style = {
  myButton: {
    color: 'green'
  }
}

// Compile styles, apply plugins.
const sheet = jss.createStyleSheet(style)

// If you want to render on the client, insert it into DOM.
sheet.attach()

// If you want to render server-side, get the CSS text.
sheet.toString()
```

```
$ node test.js
file:///Users/jim/dev/jameshfisher/test/test.js:4
jss.setup(preset())
          ^

TypeError: preset is not a function
    at file:///Users/jim/dev/jameshfisher/test/test.js:4:11
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Weirdly, this works:

```
import jssModule from 'jss'
import presetModule from 'jss-preset-default'

const jss = jssModule.default
const preset = presetModule.default

jss.setup(preset())

// Create your style.
const style = {
  myButton: {
    color: 'green'
  }
}

// Compile styles, apply plugins.
const sheet = jss.createStyleSheet(style)

// If you want to render server-side, get the CSS text.
console.log(sheet.toString())
```

__Versions (please complete the following information):__
 - jss: 10.8.1
 - Browser [e.g. chrome, safari]:
 - OS [e.g. Windows, macOS]: macOS

**Comment by icy-comet** [comment]
Any update on this issue?

I am facing the same issue when using CommonJS `require` method to load JSS in. I have to do it this way to access the JSS instance:
```js
const jss = require("jss").default;
const preset = require("jss-preset-default").default;
jss.setup(preset());
```

I took a quick look at the file (`jss/dist/jss.cjs.js`) which the `main` field in the `package.json` points to, and I guess `rollup` is the one causing the problem here. Here's how it defines the exports in the compiled `cjs` file:

```js
/**
 * A better abstraction over CSS.
 *
 * @copyright Oleg Isonen (Slobodskoi) / Isonen 2014-present
 * @website https://github.com/cssinjs/jss
 * @license MIT
 */
var index = createJss();

exports.RuleList = RuleList;
exports.SheetsManager = SheetsManager;
exports.SheetsRegistry = SheetsRegistry;
exports.create = createJss;
exports.createGenerateId = createGenerateId;
exports.createRule = createRule;
exports.default = index;
exports.getDynamicStyles = getDynamicStyles;
exports.hasCSSTOMSupport = hasCSSTOMSupport;
exports.sheets = sheets;
exports.toCssValue = toCssValue;
```

**Comment by ricovitch** [comment]
Since we updated our design system build with rollup v3, we are seeing this issue as well in tests of projects using the design system library.

The jest tests work fine in our own codebase, but when using jest in a create-react-app template project (react-scripts v5 with node 16.17), we observe the same error : "TypeError: preset is not a function"
