### ISSUE TITLE
[cli] Parse error when using filename as a path

### ISSUE THREAD

**Issue by viattik** [cssinjs/jss#573]
Getting parsing error:
```
~/P/g/j/c/css> jss convert style.css -f js -e es6 > style.js
/usr/local/lib/node_modules/jss-cli/node_modules/css/lib/parse/index.js:72
      throw err;
      ^

Error: undefined:1:10: missing '{'
    at error (/usr/local/lib/node_modules/jss-cli/node_modules/css/lib/parse/index.js:62:15)
    at declarations (/usr/local/lib/node_modules/jss-cli/node_modules/css/lib/parse/index.js:247:25)
    at rule (/usr/local/lib/node_modules/jss-cli/node_modules/css/lib/parse/index.js:560:21)
    at rules (/usr/local/lib/node_modules/jss-cli/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/usr/local/lib/node_modules/jss-cli/node_modules/css/lib/parse/index.js:81:21)
    at Object.module.exports [as parse] (/usr/local/lib/node_modules/jss-cli/node_modules/css/lib/parse/index.js:564:20)
    at module.exports (/usr/local/lib/node_modules/jss-cli/lib/cssToJss.js:12:17)
    at convert (/usr/local/lib/node_modules/jss-cli/bin/jss.js:40:19)
    at Command.onConvert (/usr/local/lib/node_modules/jss-cli/bin/jss.js:82:26)
    at Command.listener (/usr/local/lib/node_modules/jss-cli/node_modules/commander/index.js:300:8)
```
But works fine when using './filename' instead:
```
~/P/g/j/c/css>
jss convert ./style.css -f js -e es6 > ./style.js
```

CLI version - 4.2.1.

**Comment by kof** [comment]
Seems like we don't resolve paths when there is no dot.
