### ISSUE TITLE
[jss-default-unit] Babel issue

### ISSUE THREAD

**Issue by kalinchernev** [cssinjs/jss#660]
Hi, I was following the [installation guide from material-ui@next](https://material-ui-next.com/getting-started/installation/), tried to start my project and got the following error:

I've replaced a long path with foo one, the rest is unchanged.

Node version: `v8.9.3` (with nvm)

Tried to remove the `node_modules` and re-install, but sill getting the same error.

```
🚨  /foo-project-location/node_modules/jss-default-unit/lib/index.js: Unknown plugin "transform-es3-member-expression-literals" specified in "/foo-project-location/node_modules/jss-default-unit/.babelrc" at 0, attempted to resolve relative to "/foo-project-location  at /foo-project-location/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/foo-project-location/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/foo-project-location/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/foo-project-location/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/foo-project-location/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/foo-project-location/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/foo-project-location/node_modules/parcel-bundler/src/assets/JSAsset.js:60:20)
    at <anonymous>
```

**Comment by kof** [comment]
You should not run your babel over node_modules.

**Comment by kalinchernev** [comment]
@kof thank you, the issue appeared to be well-known for the [parcel bundler](https://github.com/parcel-bundler/parcel/issues/13).
