### ISSUE TITLE
JSS trying to call non-functions? (TypeError: Object(...) is not a function)

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#847]
JSS 3.11.1

__Expected behavior:__

No errors.

__Describe the bug:__

This is my style:

```js
function style() { return {
  mapperLogo: {
    display: 'block',
    position: 'absolute',
    top: '50%',
    left: 0,
    transform: translate( 0, '-50%' ),

    '& img': {
      display: 'block',
    },
  },

  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    backgroundColor: '#f1f1f1',
    zIndex: 100,

    // [media('<desktop')]: {
    //   height: px(100),
    // },

    // [media('>=desktop')]: {
    //   height: px(50),
    //   textAlign: 'left',
    // },

    opacity: 1,
    transition: 'opacity 200ms',

    // '@supports ( -webkit-backdrop-filter: blur(40px) ) or ( backdrop-filter: blur(40px) )': {
    //   opacity: 0.8,
    // },

    // backdropFilter: blur(px(40)),

    '&.faded': {
      opacity: 0.8,
      transition: 'opacity 200ms',
    },
  },
}}
```

I am using it with `@injectStyle(style)` on a React component with react-jss.

When I uncomment any of the commented blocks, it looks like JSS is trying to call my objects as functions (for some reason?).

For example, if I uncomment the line,

```js
    backdropFilter: blur(px(40)),
```

(The `blur` function is from `css-functions`, and the return value of `px()` is a string)

then I get

```
TypeError: Object(...) is not a function
    at style (src/components/Header.tsx:214:0)
    at getStyles (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-jss/lib/createHoc.js:84:10)
    at Jss.createState (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-jss/lib/createHoc.js:220:24)
    at new Jss (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-jss/lib/createHoc.js:146:27)
    at processChild (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2369:14)
    at resolve (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2335:5)
    at ReactDOMServerRenderer.render (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2657:22)
    at ReactDOMServerRenderer.read (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2631:23)
    at renderToString (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3022:25)
    at renderPage (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/dist/server/render.js:275:26)
    at Function.getInitialProps (src/pages/_document.tsx:23:0)
    at _callee$ (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/dist/lib/utils.js:111:30)
    at tryCatch (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
```

where `Header.tsx:214` is exactly that line.

Any ideas?

__Codesandbox link:__ 

Not sure how to reproduce, I have to make a small reproduction and right now I have a large private code base.

__Versions (please complete the following information):__
 - jss: 3.11.1

**Comment by trusktr** [comment]
Oops, nevermind, `css-functions` does not have `blur`!
